
# From Playing Atari with Six Neurons: https://arxiv.org/abs/1806.01363
def get_selected_atari_list():
    return [
        'ALE/DemonAttack-v5',
        'ALE/FishingDerby-v5',
        'ALE/Frostbite-v5',
        'ALE/Kangaroo-v5',
        'ALE/NameThisGame-v5',
        'ALE/Phoenix-v5',
        'ALE/Qbert-v5',
        'ALE/Seaquest-v5',
        'ALE/SpaceInvaders-v5',
        'ALE/TimePilot-v5'
    ]

# From Agent57: https://arxiv.org/abs/2003.13350
def get_full_atari_list():
    return [
        'ALE/Alien-v5',
        'ALE/Amidar-v5',
        'ALE/Assault-v5',
        'ALE/Asterix-v5',
        'ALE/Asteroids-v5',
        'ALE/Atlantis-v5',
        'ALE/BankHeist-v5',
        'ALE/BattleZone-v5',
        'ALE/BeamRider-v5',
        'ALE/Berzerk-v5',
        'ALE/Bowling-v5',
        'ALE/Boxing-v5',
        'ALE/Breakout-v5',
        'ALE/Centipede-v5',
        'ALE/ChopperCommand-v5',
        'ALE/CrazyClimber-v5',
        'ALE/Defender-v5',
        'ALE/DemonAttack-v5',
        'ALE/DoubleDunk-v5',
        'ALE/Enduro-v5',
        'ALE/FishingDerby-v5',
        'ALE/Freeway-v5',
        'ALE/Frostbite-v5',
        'ALE/Gopher-v5',
        'ALE/Gravitar-v5',
        'ALE/Hero-v5',
        'ALE/IceHockey-v5',
        'ALE/Jamesbond-v5',
        'ALE/Kangaroo-v5',
        'ALE/Krull-v5',
        'ALE/KungFuMaster-v5',
        'ALE/MontezumaRevenge-v5',
        'ALE/MsPacman-v5',
        'ALE/NameThisGame-v5',
        'ALE/Phoenix-v5',
        'ALE/Pitfall-v5',
        'ALE/Pong-v5',
        'ALE/PrivateEye-v5',
        'ALE/Qbert-v5',
        'ALE/Riverraid-v5',
        'ALE/RoadRunner-v5',
        'ALE/Robotank-v5',
        'ALE/Seaquest-v5',
        'ALE/Skiing-v5',
        'ALE/Solaris-v5',
        'ALE/SpaceInvaders-v5',
        'ALE/StarGunner-v5',
        'ALE/Surround-v5',
        'ALE/Tennis-v5',
        'ALE/TimePilot-v5',
        'ALE/Tutankham-v5',
        'ALE/UpNDown-v5',
        'ALE/Venture-v5',
        'ALE/VideoPinball-v5',
        'ALE/WizardOfWor-v5',
        'ALE/YarsRevenge-v5',
        'ALE/Zaxxon-v5'
    ]



def get_frames_to_skip():
    return {
        'DemonAttack-v5':   0,
        'FishingDerby-v5':  0,
        'Frostbite-v5':     16,
        'Kangaroo-v5':      40, #   (2 after)
        'NameThisGame-v5':  100,
        'Phoenix-v5':       0,
        'Qbert-v5':         40,
        'Seaquest-v5':      32,
        'SpaceInvaders-v5': 34,
        'TimePilot-v5':     32,
    }

# # From ALE: https://arxiv.org/abs/1207.4708
# def get_full_atari_list():
#     return [
#     'ALE/Alien-v5',
#     'ALE/Amidar-v5',
#     'ALE/Assault-v5',
#     'ALE/Asterix-v5',
#     'ALE/Asteroids-v5',
#     'ALE/Atlantis-v5',
#     'ALE/BankHeist-v5',
#     'ALE/BattleZone-v5',
#     'ALE/BeamRider-v5',
#     'ALE/Berzerk-v5',
#     'ALE/Bowling-v5',
#     'ALE/Boxing-v5',
#     'ALE/Breakout-v5',
#     'ALE/Carnival-v5',
#     'ALE/Centipede-v5',
#     'ALE/ChopperCommand-v5',
#     'ALE/CrazyClimber-v5',
#     'ALE/DemonAttack-v5',
#     'ALE/DoubleDunk-v5',
#     'ALE/ElevatorAction-v5',
#     'ALE/Enduro-v5',
#     'ALE/FishingDerby-v5',
#     'ALE/Freeway-v5',
#     'ALE/Frostbite-v5',
#     'ALE/Gopher-v5',
#     'ALE/Gravitar-v5',
#     'ALE/Hero-v5',
#     'ALE/IceHockey-v5',
#     'ALE/Jamesbond-v5',
#     'ALE/JourneyEscape-v5',
#     'ALE/Kangaroo-v5',
#     'ALE/Krull-v5',
#     'ALE/KungFuMaster-v5',
#     'ALE/MontezumaRevenge-v5',
#     'ALE/MsPacman-v5',
#     'ALE/NameThisGame-v5',
#     'ALE/Pooyan-v5',
#     'ALE/PrivateEye-v5',
#     'ALE/Qbert-v5',
#     'ALE/Riverraid-v5',
#     'ALE/RoadRunner-v5',
#     'ALE/Robotank-v5',
#     'ALE/Seaquest-v5',
#     'ALE/Skiing-v5',
#     'ALE/SpaceInvaders-v5',
#     'ALE/StarGunner-v5',
#     'ALE/Tennis-v5',
#     'ALE/TimePilot-v5',
#     'ALE/Tutankham-v5',
#     'ALE/UpNDown-v5',
#     'ALE/Venture-v5',
#     'ALE/VideoPinball-v5',
#     'ALE/WizardOfWor-v5',
#     'ALE/Zaxxon-v5'
# ]

# # Difference
# def get_full_atari_list():
#     return [
#         'ALE/Alien-v5',
#         'ALE/Amidar-v5',
#         'ALE/Assault-v5',
#         'ALE/Asterix-v5',
#         'ALE/Asteroids-v5',
#         'ALE/Atlantis-v5',
#         'ALE/BankHeist-v5',
#         'ALE/BattleZone-v5',
#         'ALE/BeamRider-v5',
#         'ALE/Berzerk-v5',
#         'ALE/Bowling-v5',
#         'ALE/Boxing-v5',
#         'ALE/Breakout-v5',
#         # 'ALE/Carnival-v5',
#         'ALE/Centipede-v5',
#         'ALE/ChopperCommand-v5',
#         'ALE/CrazyClimber-v5',
#         ####### ADD DEFENDER ########
#         'ALE/DemonAttack-v5',
#         'ALE/DoubleDunk-v5',
#         # 'ALE/ElevatorAction-v5',
#         'ALE/Enduro-v5',
#         'ALE/FishingDerby-v5',
#         'ALE/Freeway-v5',
#         'ALE/Frostbite-v5',
#         'ALE/Gopher-v5',
#         'ALE/Gravitar-v5',
#         'ALE/Hero-v5',
#         'ALE/IceHockey-v5',
#         'ALE/Jamesbond-v5',
#         # 'ALE/JourneyEscape-v5',
#         'ALE/Kangaroo-v5',
#         'ALE/Krull-v5',
#         'ALE/KungFuMaster-v5',
#         'ALE/MontezumaRevenge-v5',
#         'ALE/MsPacman-v5',
#         'ALE/NameThisGame-v5',
#         ###### ADD PHOENIX ######
#         ###### ADD PITFALL ######
#         ###### ADD PONG ######
#         # 'ALE/Pooyan-v5',
#         'ALE/PrivateEye-v5',
#         'ALE/Qbert-v5',
#         'ALE/Riverraid-v5',
#         'ALE/RoadRunner-v5',
#         'ALE/Robotank-v5',
#         'ALE/Seaquest-v5',
#         'ALE/Skiing-v5',
#         ###### ADD SOLARIS ######
#         'ALE/SpaceInvaders-v5',
#         'ALE/StarGunner-v5',
#         ###### ADD SURROUNG ######
#         'ALE/Tennis-v5',
#         'ALE/TimePilot-v5',
#         'ALE/Tutankham-v5',
#         'ALE/UpNDown-v5',
#         'ALE/Venture-v5',
#         'ALE/VideoPinball-v5',
#         'ALE/WizardOfWor-v5',
#         ###### ADD YARS REVENGE ######
#         'ALE/Zaxxon-v5'
#     ]
